version: "3.9"

networks:
  elk:
    driver: bridge

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elk

  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - cluster.initial_master_nodes=es01,es02,es03
      - discovery.seed_hosts=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://es01:9200
    ports:
      - 5601:5601
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5044:5044
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:8.10.2
    container_name: metricbeat
    user: root
    command: metricbeat -e -E output.elasticsearch.hosts=["http://es01:9200"] -E setup.kibana.host=http://kibana:5601
    volumes:
      - ./metricbeat/metricbeat.yaml:/usr/share/metricbeat/metricbeat.yml:ro
    networks:
      - elk
    depends_on:
      - es01
      - es02
      - es03
