# install-jenkins-slave.yml
---

- name: Run steps on Jenkins slave
  hosts: jenkinsslave
  become: true
  tasks:

    - name: Create group "jenkins"
      ansible.builtin.group:
        name: jenkins
        state: present
        system: true

    - name: Add user and change shell for user 'jenkins'
      ansible.builtin.user:
        name: jenkins
        group: jenkins
        comment: Jenkins Automation Server
        home: /var/lib/jenkins
        shell: /bin/bash
        state: present 

    - name: Create a workspace directory
      ansible.builtin.file:
        path: /var/lib/jenkins/jenkins_workspace
        state: directory
        mode: '0755'
        owner: jenkins
        group: jenkins

    - name: Download files for Maven
      get_url:
        url: https://www-eu.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
        dest: /opt
    
    - name: Extract downloaded archive
      ansible.builtin.unarchive:
        src: /opt/apache-maven-3.6.3-bin.tar.gz
        dest: /opt
        remote_src: yes        

    - name: Create symbolic link 
      file:
        src: "apache-maven-3.6.3"
        dest: "/opt/maven"
        state: link

    - name: Create file
      ansible.builtin.blockinfile:
        path: /etc/profile.d/maven.sh
        create: yes
        mode: '0755'
        insertbefore: BOF
        block: |
          export M2_HOME=/opt/maven
          export PATH=${M2_HOME}/bin:${PATH}

    - name: Source the maven script
      shell: "source /etc/profile.d/maven.sh"

    - name: Installs git, java
      yum:  
        name: 
          - git
          - java-11-openjdk-devel
        state: present
