# installs tomcat - needed for Jenkins lab
---

- name: Install tomcat
  hosts: jenkins
  become: true
  tasks:

    - name: Ensure group "tomcat" exists
      ansible.builtin.group:
        name: tomcat
        state: present
        system: true

    - name: Add user+group for Tomcat
      ansible.builtin.user:
        name: tomcat
        shell: /bin/false
        groups: tomcat
        home: /usr/local/tomcatlink
        state: present   

    - name: Get latest version of Tomcat and set in variable
      set_fact:
        ver: 9.0.58

    - name: Download files for Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v{{ ver }}/bin/apache-tomcat-{{ ver }}.tar.gz
        dest: /usr/local

    - name: Extract downloaded archive for Tomcat
      ansible.builtin.unarchive:
        src: /usr/local/apache-tomcat-{{ ver }}.tar.gz
        dest: /usr/local
        remote_src: yes    
        owner: tomcat 
        group: tomcat          

    - name: Create symbolic link for Tomcat - Getting error so create dir dirst
      ansible.builtin.file:
        src: /usr/local/apache-tomcat-{{ ver }}
        name:  /usr/local/tomcatlink
        state: directory
        # force: yes     

    - name: Empty dir
      ansible.builtin.file:
        src: /usr/local/apache-tomcat-{{ ver }}
        name: /usr/local/tomcatlink
        state: absent
        # force: yes  

    - name: Create symbolic link for Tomcat
      ansible.builtin.file:
        src: /usr/local/apache-tomcat-{{ ver }}
        name: /usr/local/tomcatlink
        state: link  
        owner: tomcat 
        group: tomcat
        force: yes     

    - name: Set ownership of symbolic link for Tomcat
      ansible.builtin.file:
        name: /usr/local/tomcatlink
        state: link  
        owner: tomcat 
        group: tomcat

    - name: Create /etc/systemd/system/tomcat.service
      copy:
        dest: "/etc/systemd/system/tomcat.service"
        content: |
          [Unit]
          Description=Apache Tomcat Server
          After=syslog.target network.target

          [Service]
          Type=forking
          User=tomcat
          Group=tomcat

          Environment=CATALINA_PID=/usr/local/tomcatlink/temp/tomcat.pid
          Environment=CATALINA_HOME=/usr/local/tomcatlink
          Environment=CATALINA_BASE=/usr/local/tomcatlink

          ExecStart=/usr/local/tomcatlink/bin/catalina.sh start
          ExecStop=/usr/local/tomcatlink/bin/catalina.sh stop

          RestartSec=10
          Restart=always
          [Install]
          WantedBy=multi-user.target

    - name: Change tomcat port to use 8081
      ansible.builtin.replace:
        path: /usr/local/apache-tomcat-{{ ver }}/conf/server.xml
        regexp: '(\s+)<Connector port="8080"(\s+.*)'
        replace: '\1<Connector port="8081"\2'        

    # Uncomment play below if you have firewalld
    # - name: FirewallD rules
    #   firewalld:
    #     permanent: yes
    #     immediate: yes
    #     port: 8081/tcp
    #     zone: public
    #     state: enabled

    - name: Configure users on tomcat-users.xml
      ansible.builtin.lineinfile:
        path: /usr/local/tomcatlink/conf/tomcat-users.xml
        insertbefore: "^</tomcat-users>"
        line: |
          <role rolename="admin-gui"/>
          <role rolename="manager-gui"/>
          <user username="tomcat1" password="tomcat1993" roles="admin-gui,manager-gui,manager-script"/>

    - name: Enable Remote Access to Tomcat Manager 
      ansible.builtin.lineinfile:
        path: /usr/local/apache-tomcat-{{ ver }}/webapps/manager/META-INF/context.xml
        regexp: 'allow="127\.\d+\.\d\+\.\d\+|::1|0:0:0:0:0:0:0:1" />'
        line: '         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1 |.*" />'        
        state: present

    - name: Enable Remote Access to Tomcat Host-manager 
      ansible.builtin.lineinfile:
        path: /usr/local/apache-tomcat-{{ ver }}/webapps/host-manager/META-INF/context.xml
        regexp: 'allow="127\.\d+\.\d\+\.\d\+|::1|0:0:0:0:0:0:0:1" />'
        line: '         allow="127\.\d+\.\d+\.\d+|::1|0:0:0:0:0:0:0:1 |.*" />'        
        state: present

    - name: Force systemd to reread configs
      systemd:
        daemon_reload: yes

    - name: Ensures Tomcat is started
      systemd:
        name: tomcat
        enabled: yes
        state: started