---
- name: Test
  hosts: localhost
  vars:
    data:
      chris:
        name: testeden1
        salary: 46000
        age: 27
      jessy:
        name: testeden2
        salary: 70000
        age: 30

  tasks:
  - name: Check that you can connect (GET) to a page and it returns a status 200
    uri:
      method: GET
      url: "http://dummy.restapiexample.com/api/v1/employees"
      return_content: yes
      headers:
        Accept: application/json
    register: response

  - debug:
      msg: "{{ response.content }}"
      