Comptia Security:
  label: 'Comptia Security'
  permalink: '/Comptia Security'
  description: 'Docs related to Comptia Security'   
CISSP:
  label: 'CISSP'
  permalink: '/CISSP'
  description: 'Docs related to CISSP'    
Security:
  label: 'Security'
  permalink: '/Security'
  description: 'Docs related to Security' 
Cybersecurity:
  label: 'Cybersecurity'
  permalink: '/Cybersecurity'
  description: 'Docs related to Cybersecurity'   
Asset Security:
  label: 'Asset Security'
  permalink: '/Asset Security'
  description: 'Docs related to Asset Security'
Network Security:
  label: 'Network Security'
  permalink: '/Network Security'
  description: 'Docs related to Network Security'   
Data Security:
  label: 'Data Security'
  permalink: '/Data Security'
  description: 'Docs related to Data Security'   
Software Development Security:
  label: 'Software Development Security'
  permalink: '/Software Development Security'
  description: 'Docs related to Software Development Security'       
Vulnerability Management:
  label: 'Vulnerability Management'
  permalink: '/Vulnerability Management'
  description: 'Docs related to Vulnerability Management'    
Penetration Testing:
  label: 'Penetration Testing'
  permalink: '/Penetration Testing'
  description: 'Docs related to Penetration Testing'   
Security Assessment:
  label: 'Security Assessment'
  permalink: '/Security Assessment'
  description: 'Docs related to Security Assessment'   
Digital Forensics:
  label: 'Digital Forensics'
  permalink: '/Digital Forensics'
  description: 'Docs related to Digital Forensics'  
Incident Response:
  label: 'Incident Response'
  permalink: '/Incident Response'
  description: 'Docs related to Incident Response'   
Security Operations:
  label: 'Security Operations'
  permalink: '/Security Operations'
  description: 'Docs related to Security Operations'    
Security Architecture:
  label: 'Security Architecture'
  permalink: '/Security Architecture'
  description: 'Docs related to Security Architecture'  
Security Engineering:
  label: 'Security Engineering'
  permalink: '/Security Engineering'
  description: 'Docs related to Security Engineering'    

Security Testing:
  label: 'Security Testing'
  permalink: '/Security Testing'
  description: 'Docs related to Security Testing'  
PAM:
  label: 'PAM'
  permalink: '/PAM'
  description: 'Docs related to PAM'    
IAM:
  label: 'IAM'
  permalink: '/IAM'
  description: 'Docs related to IAM'  
Risk Management:
  label: 'Risk Management'
  permalink: '/Risk Management'
  description: 'Docs related to Risk Management'
Business Continuity:
  label: 'Business Continuity'
  permalink: '/Business Continuity'
  description: 'Docs related to Business Continuity'  
System Hardening:
  label: 'System Hardening'
  permalink: '/System Hardening'
  description: 'Docs related to System Hardening'  
Access Management:
  label: 'Access Management'
  permalink: '/Access Management'
  description: 'Docs related to Access Management'    
Access Control:
  label: 'Access Control'
  permalink: '/Access Control'
  description: 'Docs related to Access Control' 
Cryptography:
  label: 'Cryptography'
  permalink: '/Cryptography'
  description: 'Docs related to Cryptography'     
Disaster Recovery:
  label: 'Disaster Recovery'
  permalink: '/Disaster Recovery'
  description: 'Docs related to Disaster Recovery'